"""Add style_profile to users

Revision ID: 63fb12e332ae
Revises: 0002
Create Date: 2026-08-28 23:11:18.797552

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fb12e332ae'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_feedback_student_id'), 'tutor_feedback', ['student_id'], unique=False)
    op.create_index(op.f('ix_tutor_feedback_timestamp'), 'tutor_feedback', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tutor_feedback_topic_id'), 'tutor_feedback', ['topic_id'], unique=False)
    op.add_column('users', sa.Column('style_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'style_profile')
    op.drop_index(op.f('ix_tutor_feedback_topic_id'), table_name='tutor_feedback')
    op.drop_index(op.f('ix_tutor_feedback_timestamp'), table_name='tutor_feedback')
    op.drop_index(op.f('ix_tutor_feedback_student_id'), table_name='tutor_feedback')
    op.drop_table('tutor_feedback')
    # ### end Alembic commands ###
